name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install apt-file to find packages
      run: sudo apt-get install apt-file
    - name: Update apt-file database
      run: sudo apt-file update
    - name: Install db devel files
      run: sudo apt-get install $(sudo apt-file -l search /usr/include/db.h)
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
